version = 1

test_patterns = ["tests/**", "end_to_end_tests/**"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "black"
enabled = true
