version = 1

test_patterns = ["tests/**", "end_to_end_tests/**"]
exclude_patterns = ["tests/test_templates/*", "end_to_end_tests/golden-master/**"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 120
  type_checker = "mypy"

